### PR TITLE
profile page features

### PR DESCRIPTION
**Pull request by Toastjpg**
- Add profile service
- Add content to profile page to edit profile data

### CODE REVIEW

**Review by jerrydngzh — APPROVED** [review]
lgtm

**Comment by Toastjpg** [comment]
@jerrydngzh extracted code into components. Ready to merge now.

Leaving the styling as it is now. Will also add memo related info on profile like recently created/pinned. Will wait until memo creation/management features are closer to being finalized.

**Review by jerrydngzh — APPROVED** [review]
noticed alot of the wrapper types for primitives like `String` -> `string`. Was this a `prettier` auto format?

otherwise lgtm

**Comment by Toastjpg** [comment]
`String` is the javascript string object but `string` with lowercase s is the typescript primitive type

**Pull request merged**
